### PR TITLE
fix: fire done logic when percent is 1, instead of using the compiler "done" hook

### PR DESCRIPTION
**Pull request by charlessuh**
It looks like in webpack@4, the compiler "done" hook sets progress percentage to 1: https://github.com/webpack/webpack/blob/v4.46.0/lib/ProgressPlugin.js#L291-L293 but in webpack@5, there are some additional cache steps that were added such that it doesn't represent progress 1: https://github.com/webpack/webpack/blob/v5.62.2/lib/ProgressPlugin.js#L569-L574

This seems to be cause of https://github.com/unjs/webpackbar/issues/83

### CODE REVIEW

**Comment by hewenguang** [comment]
@pi0

**Comment by uki1014** [comment]
@pi0 👀

**Comment by AkiJoey** [comment]
@pi0

**Comment by shuaiqidekaige** [comment]
@pi0

**Pull request closed without merging**
